# fly.toml app configuration file generated for domain-name-resolver on 2024-11-23T11:50:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'domain-name-resolver'
primary_region = 'fra'

[build]
  image = 'domain_name_resolver:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
